spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update

device-cookie:
  time-window: PT1M
  max-failures: 2
  penalty-duration: PT5M
  nonce-length: 32
  jwt:
    issuer: http://test.pl
    secret: j+x1Wvn/Dz/AZOqFj/nBsSOUKutXQvhag55MpLESVtI=

security:
  predefined-users:
    - username: admin
      password: admin
      roles:
        - ADMIN
    - username: user1
      password: pass
      roles:
        - USER
    - username: user2
      password: pass
      roles:
        - USER

logging:
  level:
    pl.recompiled: DEBUG

---

spring:
  config:
    activate.on-profile: integration-tests

  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update

device-cookie:
  time-window: PT30M
  max-failures: 5
  penalty-duration: PT1H
  nonce-length: 32
  jwt:
    issuer: http://test.pl
    secret: j+x1Wvn/Dz/AZOqFj/nBsSOUKutXQvhag55MpLESVtI=

security:
  predefined-users:
    - username: user
      password: pass
      roles:
        - USER