
spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update

device-cookie:
  time-window: PT1M
  max-failures: 2
  penalty-duration: PT5M
  nonce-length: 32
  jwt:
    issuer: http://test.pl
    secret: j+x1Wvn/Dz/AZOqFj/nBsSOUKutXQvhag55MpLESVtI=